force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>ENR-{0000}</displayFormat>
        <label>Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Fees_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fees_Amount__c</fullName>
    <label>Fees Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentServiceTest.cls
@isTest
public class PaymentServiceTest {

    @isTest
    static void testPaymentTotal()
    {
        // Create Course
        Course__c c = new Course__c(
            Name = 'Java',
            Available_Seats__c = 10
        );
        insert c;

        // Create Student
        Student__c s = new Student__c(
            Name = 'Test Student'
        );
        insert s;

        // Create Enrollment
        Enrollment__c e = new Enrollment__c(
            Student__c = s.Id,
            Course__c = c.Id,
            Fees_Amount__c = 1000
        );
        insert e;

        // Create Payment
        Payment__c p1 = new Payment__c(
            Enrollment__c = e.Id,
            Amount__c = 500,
            Payment_Status__c = 'Paid'
        );
        insert p1;

        Payment__c p2 = new Payment__c(
            Enrollment__c = e.Id,
            Amount__c = 300,
            Payment_Status__c = 'Paid'
        );
        insert p2;

        // Call Apex Class
        Decimal total = PaymentService.getTotalPayment(e.Id);

        System.assertEquals(800, total);
    }
@isTest
static void testPaymentCount()
{
    Course__c c = new Course__c(
        Name = 'Python',
        Available_Seats__c = 5
    );
    insert c;

    Student__c s = new Student__c(
        Name = 'Student 2'
    );
    insert s;

    Enrollment__c e = new Enrollment__c(
        Student__c = s.Id,
        Course__c = c.Id,
        Fees_Amount__c = 2000
    );
    insert e;

    Payment__c p = new Payment__c(
        Enrollment__c = e.Id,
        Amount__c = 1000,
        Payment_Status__c = 'Paid'
    );
    insert p;

    Integer countPay = PaymentService.getPaymentCount(e.Id);

    System.assertEquals(1, countPay);
}
}